### PR TITLE
issue 26

### PR DESCRIPTION
**Pull request by berstearns**
- **added 3 mkdocs related packages, mkdocs, mkdocstrings, mkdocs-material**
- **mkdocs project minimal configuration**
- **suggested pages for the documentation following https://diataxis.fr/**
- **adding plugin to create pages automatically for each module**
- **adding auto nav generator for code**
- **code reference pages generator**
- **added references folder as automatic generated code docs**
- **replaced current docs of corpus.py with google docs format**
- **dummy example page using manually a docstring from the source code**
- **adding teanga logo for index page**
- **automatically generated toc identifiers for usage in docs**
- **setup minimal structure for nav with navigations features  using material docs, added teanga icon, added github icon, added dummy sections to be created**
- **manual nav automatic docstrings**
- **removing the automatic generation of md files for the code reference in favor of manually creating one file for each module**
- **added one generic code docs for each module. minor changes to description on index page**
- **converted the docs to tab based docs**
- **manually added teanga modules mds to nav**
- **adding utils docs**
- **moved src content for the mkdocs to a src folder**
- **suggested path to docs. need to merge to main first to trigget deployment**

### CODE REVIEW

**Comment by berstearns** [comment]
Pytest failed for the changes in the doctest. Need to double check the pytest to verify the new doctest format

**Comment by jmccrae** [comment]
@berstearns The PyTest is dependent on the formatting of the output (as it does exact string matches). Some changes to the formatting of the examples changes the tests. Can you fix and we can merge?

**Comment by berstearns** [comment]
Will do, just didn't have the time yet. Just wanted to comment it out to check when I have the time.

**Comment by berstearns** [comment]
@jmccrae  I think the doctstring is now consistent across all py files in the teanga/ folder.  I guess we can merge this PR into master as the first working mkdocs version and I will create a new issue on CD the mkdocs to the github page (teanga.io) ?

**Pull request merged**
